[package]
name = "rustifacts"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
walkdir = "2.5.0"
anyhow = "1.0.86"
log = "0.4.22"
env_logger = "0.11.5"
thiserror = "1.0.63"
tempfile = "3.12.0"